### PR TITLE
Adds node-exporters

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/giantswarm/issues/1482

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
Successfully tested on `gauss` via https://github.com/giantswarm/aws-operator/pull/593, `node-exporters` come up correctly

screen shot 2017-12-20 at 16 31 34

**Comment by JosephSalisbury** [comment]
And that's wayyyyyy too many people on the review :D

**Comment by r7vme** [comment]
> We finally decided we don't change non-latest versions (i.e. v_2_0_0).

Would like to see public announce if smth like that was decided.

For me it looks like temporary agreement until we define our upgrade strategy. 1) We still dont have instruments to update current clusters if we freeze directories 2) It's still hard to test v3_0_0 as code changes in operator required to use v3_0_0.

Let's talk about it.

**Comment by JosephSalisbury** [comment]
Closing here. Old, and I need to rework it somewhat.

**Pull request closed without merging**
