### PR TITLE
Remove profiling from Controller Manager and Scheduler

### PR DESCRIPTION
**Pull request by stone-z**
Towards https://github.com/giantswarm/giantswarm/issues/4813
Removes the debug profiling endpoint at /debug/pprof for Controller Manager and Scheduler

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by stone-z** [comment]
Also double-checking with @giantswarm/sig-monitoring that these debug endpoints aren't being scraped or used somewhere for monitoring.

**Comment by tuommaki** [comment]
>  aren't being scraped or used somewhere for monitoring.

Nope. Only occasionally used for debugging resource overuse.

**Comment by omegas27** [comment]
@tfussell was releasing v6.0.3. You might want to merge into it but it looks fine to me. It would be nice to be able to enable it if needed in the future though

**Comment by stone-z** [comment]
> It would be nice to be able to enable it if needed in the future though

Is it helpful enough to be made configurable? If we use it often enough then I could revisit it as an argument. 
I don't think changing it at this level would be super useful because this would be set at node creation time, so if you wanted to turn it on for debugging you'd either have to create a new node or restart the component manually with the flag re-applied (which you can already do).

**Comment by omegas27** [comment]
Maybe doing it manually works in this case, It was just a thought of mine

**Comment by stone-z** [comment]
Sure, if it's worth making it configurable let's revisit

**Pull request merged**
