### PR TITLE
adding kubelet and proxy to master

### PR DESCRIPTION
**Pull request by puja108**
WIP

towards https://github.com/giantswarm/k8scloudconfig/issues/116

### CODE REVIEW

**Comment by puja108** [comment]
Todos:

- [ ] add kubeconfig.yaml for kubelet to `/etc/kubernetes/config/`
- [ ] add kubeconfig.yaml for proxy to `/etc/kubernetes/config/`

**Comment by puja108** [comment]
not sure we need all that waiting for calico and things in there, but for now I'd like to just get that kubelet working, and we can handle calico move afterwards.

RFR

**Comment by rossf7** [comment]
Thanks @puja108 I'll launch a cluster with this cloudconfig to test. Agree on removing the calico waits later.

**Comment by puja108** [comment]
first testing looks good, next would be launching a full cluster on aws with this

**Pull request merged**
