### PR TITLE
double fs.inotify.max_user_watches

### PR DESCRIPTION
**Pull request by jgsqware**
Related to this PM
https://github.com/giantswarm/giantswarm/issues/4777

This PR double the inotify watches

Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>

### CODE REVIEW

**Comment by jgsqware** [comment]
Is this the right version upgraded? Do I have to vendor all the operator or can it be done later as it's not a critical change?

**Comment by xh3b4sd** [comment]
I am not too much into the PM but when this is a fix we want to have in all further versions it has to at least land in `v_4_0_0` because this is the folder that will be copied to make up new versions. Right now your fix is not in there.

**Comment by rossf7** [comment]
@jgsqware I want to clean up the YAMLs in 3.7.2 for https://github.com/giantswarm/giantswarm/issues/4833. So I can take the copying foo and add 3.7.3.

**Comment by jgsqware** [comment]
Closing in favor of https://github.com/giantswarm/k8scloudconfig/pull/478

**Pull request closed without merging**
