### PR TITLE
fix etcd data creation

### PR DESCRIPTION
**Pull request by jgsqware**
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>

Wait for etcd data directory creation before setting permission

### CODE REVIEW

**Comment by calvix** [comment]
is this tested? in my head it's looks wrong

**Comment by xh3b4sd** [comment]
What exactly looks wrong to you?

**Comment by calvix** [comment]
The logic that is used there.
We need to basically wait for the mount of etcd-data in kvm.
Waiting for the folder is not enough as the folder will be always there (because it was created by the mkdir in command above).

We could add some `drop-in` service unit into kvm-operator which will add dependency for etcd change owner ship unit (for example `After=`) on the mount unit.

**Comment by jgsqware** [comment]
@calvix WDYT? tested and it works. waiting this to merge those https://github.com/giantswarm/kvm-operator/pull/273

**Comment by calvix** [comment]
I don't think this change is really necessary.

for aws it works without this (because the folder is created by the command one line above) and on KVM we wait until the mount is finished so we are fine.

**Comment by jgsqware** [comment]
ok Closing this

**Pull request closed without merging**
