### PR TITLE
Use kubernetes 1.16.7

### PR DESCRIPTION
**Pull request by fiunchinho**

### CODE REVIEW

**Comment by MarcelMue** [comment]
@fiunchinho Why was this only merged into `5_1_1` and not `5_2_0`?

**Comment by fiunchinho** [comment]
It was decided that it was a _patch_ change, not a minor, so the other was dropped.

**Comment by fiunchinho** [comment]
Oh I thought you were talking about a PR to create 5_3_0 that was dropped. I see your point. We'll fix it.

**Comment by fiunchinho** [comment]
I just submitted this https://github.com/giantswarm/k8scloudconfig/pull/669

**Pull request merged**
