### PR TITLE
enable proxy protocol for ingress-nginx

### PR DESCRIPTION
**Pull request by fgimenez**
Towards https://github.com/giantswarm/giantswarm/issues/1952

### CODE REVIEW

**Comment by fgimenez** [comment]
@r7vme thx, about the implementation in AWS indeed, it is explained in the issue https://github.com/giantswarm/giantswarm/issues/1952, we need to add to the ELB a policy with the `ProxyProtocol` attribute set to `true` if it's not already applied, I'm checking it right now.

**Comment by rossf7** [comment]
This will enable proxy protocol on all clusters. Is this also OK on KVM?

**Comment by calvix** [comment]
I have concerns about KVM, this needs to be properly tested on some of our customers before we can merge.

**Comment by fgimenez** [comment]
Thx @calvix, can i perform this testing?

**Comment by calvix** [comment]
sure

**Comment by fgimenez** [comment]
Tested on lycan

**Pull request merged**
