### PR TITLE
Enable `anonymous-auth` in API server 

### PR DESCRIPTION
**Pull request by whites11**
This is needed by kubeadm

### CODE REVIEW

**Review by puja108 — APPROVED** [review]
I'm fine with enabling this as upstream and CIS benchmark also are ok with this as long as RBAC is on and tight and it does enable some features. We just need to keep in mind that our CVE exposure might be a bit higher with this cc @giantswarm/sig-security

**Comment by MarcelMue** [comment]
Why did we merge this before checking CIS?

Pretty sure we removed it BECAUSE it fails CIS:
https://github.com/giantswarm/k8scloudconfig/pull/224

**Comment by whites11** [comment]
I though we made the CIS tests already @puja108 ?

**Comment by puja108** [comment]
from most recent CIS:

> If you are using RBAC authorization, it is generally considered reasonable to allow anonymous access to the API Server for health checks and discovery purposes, and hence this recommendation is not scored. However, you should consider whether anonymous discovery is an acceptable risk for your purposes.

It is not scored as long as you have RBAC in place

**Comment by puja108** [comment]
For reference, see page 51/52 [CIS_Kubernetes_Benchmark_v1.6.1.pdf](https://github.com/giantswarm/k8scloudconfig/files/6170147/CIS_Kubernetes_Benchmark_v1.6.1.pdf)

**Pull request merged**
