### PR TITLE
Upgrade kubernetes version to 1.8.4

### PR DESCRIPTION
**Pull request by pipo02mix**

### CODE REVIEW

**Comment by pipo02mix** [comment]
Do you want me to run conformance tests? Which ones?

I have done manually testing, deploying an app (frontend/backend)

**Comment by pipo02mix** [comment]
I have run conformance tests there
```
<testsuite tests="125" failures="0" time="2732.256172625">
```

**Comment by calvix** [comment]
@pipo02mix could you also update the kubectl image we are using so we have them in same version?

**Comment by pipo02mix** [comment]
@calvix I dont find the image on coreos repo. I have taken one from docker hub (roffee) with the 1.8.4. (BTW I dont find the image in retagger either so I add it too)

**Comment by JosephSalisbury** [comment]
See https://github.com/giantswarm/docker-kubectl

**Comment by pipo02mix** [comment]
Everything ok?

cc @JosephSalisbury @calvix

**Pull request merged**
