### PR TITLE
v_3_2_5: updated Calico to 3.0.5

### PR DESCRIPTION
**Pull request by r7vme**
There were number of bugfixes from 3.0.2

https://docs.projectcalico.org/v3.0/releases/

### CODE REVIEW

**Comment by calvix** [comment]
@r7vme could you possible bump also for host cluster?

**Comment by r7vme** [comment]
Sure, will do tomorrow. Forgot

**Comment by calvix** [comment]
:heart:

**Comment by r7vme** [comment]
In CI testing phase https://github.com/giantswarm/giantnetes-terraform/pull/75

**Comment by r7vme** [comment]
Hive: https://github.com/giantswarm/hive/pull/265

**Pull request merged**
