### PR TITLE
New WIP patch version v_3_1_1

### PR DESCRIPTION
**Pull request by r7vme**
I see potential in doing patch changes in batches.

This change just adds "dev"/WIP version for future patches.

First candidate is new Calico 3.0.2 cc: @calvix

### CODE REVIEW

**Comment by corest** [comment]
Not sure about this approach. We have this copy magic as one step just to make PRs cleaner. Now this one, which actually doesn't bring any change.

**Comment by kopiczko** [comment]
Doesn't bring any change, but makes futher PRs way cleaner.

**Comment by corest** [comment]
We can just put bumping version into the first commit and then bring some changes with next commits to see why this PR was created

**Comment by kopiczko** [comment]
To make the actual changes PR cleaner. This isn't maybe a representative example. Look at https://github.com/giantswarm/kvm-operator/commit/96d7bc329c4752e6d2d044fd4ab17058d418c1d9 & https://github.com/giantswarm/kvm-operator/commit/783d200305854779024c1b7d4ef73f0844dd96e2

I prefer having this changes separated. Otherwise it's very difficult to review.

**Comment by calvix** [comment]
i think we should automatize this in script or something,   In few months there will be 10 steps that need to be done and so much thinking around this.

**Comment by xh3b4sd** [comment]
There is already a script for the operators and really decent documentation. I suggest you use and read it. Then we can talk about further improvements.

**Pull request merged**
