### PR TITLE
Enrich template error with stacktraces

### PR DESCRIPTION
**Pull request by mazzy89**
This could help to debug the still annoying issue with cloudconfig template appeared yesterday in e2e test

### CODE REVIEW

**Comment by mazzy89** [comment]
I put it under `v4_0_0`. I think I should also port to `4_1_0` right?

**Comment by xh3b4sd** [comment]
Towards the version, We should at least do it in the latest version. When you want to backport it further, go for it.

**Comment by mazzy89** [comment]
Regarding the version, `v4_1_0` is still not used.

**Comment by xh3b4sd** [comment]
The rational is basically that when you have changes in the latest version, based on the current versioning approach, somebody will copy the latest version and make a new one. When you change the penultimate version, that changes will not make it into the new versions. So what you want to have propagated should go to the latest version. Beyond that, we can decide if something should be back ported to other versions as well.

**Comment by xh3b4sd** [comment]
Note that there is also `render_asset_content.go` missing. Then we have ALL errors I guess.

**Comment by mazzy89** [comment]
Let's go 🚀

**Pull request merged**
