### PR TITLE
Use updated clustertpr structure

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#1174 Use the updated clustertpr structure in the cloud config templates

### CODE REVIEW

**Comment by nhlfr** [comment]
Please rebase your branch with master instead of pulling with merge commits,

**Comment by rossf7** [comment]
@nhlfr I'll rebase in future. Do you want me to get rid of the 2 existing merge commits?

**Comment by nhlfr** [comment]
It would be cool if you can :)

**Comment by rossf7** [comment]
Closing this. I'm going to do a fresh PR and cherry pick my commits so the history is clean.

**Pull request closed without merging**
