### PR TITLE
Update Calico CRDs to apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by tfussell**
Based on https://docs.projectcalico.org/manifests/calico.yaml

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by tfussell** [comment]
Tested in kvm-operator@master. I will cherry-pick to v9 for testing of policy-only (AWS/Azure).

**Comment by tfussell** [comment]
Tested policy-only in https://github.com/giantswarm/k8scloudconfig/pull/859.

**Comment by tfussell** [comment]
Requesting review from @giantswarm/sig-operator as this affects all provider teams.

**Review by njuettner — APPROVED** [review]
lgtm

**Review by MarcelMue — APPROVED** [review]

**Pull request merged**
