### PR TITLE
v_4_2_0

### PR DESCRIPTION
**Pull request by calvix**
v_4_2_0

### CODE REVIEW

**Comment by corest** [comment]
Is that synced with latest 4.1.1? It feels like we can lose some updates again

**Comment by calvix** [comment]
I copied 4.1.2, so   if anyone forgets to add stuff to 4.1.2 than  i think its their mistake

**Comment by corest** [comment]
Can you cherry-pick this https://github.com/giantswarm/k8scloudconfig/pull/517

**Comment by calvix** [comment]
thanks

**Pull request merged**
