### PR TITLE
Disable Server tokens in IC

### PR DESCRIPTION
**Pull request by jgsqware**
Regarding security, the current IC nginx return a `Server: nginx <version>` header, It's considered as a security breach. This fix will disable the version in the header

rel https://github.com/giantswarm/adidas/issues/327

ref: https://geekflare.com/remove-server-header-banner-nginx/

### CODE REVIEW

**Comment by r7vme** [comment]
Please add changelog

**Comment by rossf7** [comment]
@jgsqware Please make the title start with `v_3_3_2` this is so the changelog links work.

https://github.com/giantswarm/k8scloudconfig/commits/master/v_3_3_2

**Comment by r7vme** [comment]
@jgsqware do you still want to merge this?

**Comment by jgsqware** [comment]
@rossf7 @r7vme Can i merge this now?

**Comment by rossf7** [comment]
@jgsqware This should be in v_3_3_3 as v_3_3_2 is frozen. I've done the copy PR but I still need to enable it :(

I'll do that now and sorry for the hassle with the versioning.

**Pull request merged**
