### PR TITLE
kernel-hardening

### PR DESCRIPTION
**Pull request by calvix**
kernel hardening params

* sysctl kernel values see - https://github.com/giantswarm/vodafone/issues/136
* removing special groups from core user

from the ticket i have only removed - `net.ipv4.conf.all.forwarding = 0` becasue we need forwarding

### CODE REVIEW

**Comment by calvix** [comment]
The last state is tested and conformance test is having a positive result and I tested all functionality I could think of and not found any issue.

**Comment by calvix** [comment]
@xh3b4sd we could do it sam as we do it on `mayu` we have one general profile for all machines and then worker/master specific in separate files and this will get merged 
https://github.com/giantswarm/hive/blob/master/templates/last_stage_cloudconfig.yaml#L292-L296

**Comment by xh3b4sd** [comment]
I would be in favour of some operator. I remember a case where a customer's ingress controllers have been vanished from his guest cluster and nobody noticed or knew why it was gone. An operator can ensure the desired state continuously. Separating templates does not help with this problem.

**Comment by puja108** [comment]
@xh3b4sd for what you mean there's already a tool and we have an issue in sig operator: https://github.com/giantswarm/k8scloudconfig/issues/147

**Pull request merged**
