### PR TITLE
Docker CIS : 2.1

### PR DESCRIPTION
**Pull request by jgsqware**
2.1 - Ensure network traffic is restricted between containers on the default bridge

### CODE REVIEW

**Comment by puja108** [comment]
Do you have this tested and working somewhere? We should check that it does not interfere with our networking setup

**Comment by jgsqware** [comment]
I've tested with the DNS resolution. Have another test in mind?

**Comment by jgsqware** [comment]
@calvix or @r7vme It disable the docker default bridge, `docker network inspect bridge` doesn't report any container attached to it. DNS resolution and cross container communication works.
Do you think to any other tests before merge?

**Comment by r7vme** [comment]
Hold ON. It adds explicit drop to FORWARD chain.

let's discuss, as it will drop any unknow ip address traffic....

**Comment by r7vme** [comment]
Okay `icc=false` should be ok as we are not using docker briodged network.

For me it set drop on following rule, not whole system.

`-A FORWARD -i docker0 -o docker0 -j DROP`

**Comment by calvix** [comment]
ok fine :)

**Comment by jgsqware** [comment]
Close in favor of #204

**Pull request closed without merging**
