### PR TITLE
Add trusted CA into sshd config

### PR DESCRIPTION
**Pull request by corest**
Towards: https://github.com/giantswarm/giantswarm/issues/2867

### CODE REVIEW

**Comment by corest** [comment]
@calvix Nope, it will not break anything
@r7vme I'm fine with this

**Comment by corest** [comment]
@r7vme ping again

**Comment by calvix** [comment]
I see some changes to v3_4_0 files and some to v3_4_4. This wont probably work :)

**Comment by calvix** [comment]
Also I am just curious how many ppl are actually using the CA-based ssh auth :p

**Comment by corest** [comment]
Well, I can't force anyone to use that

**Comment by calvix** [comment]
I think we need to add this to `v3_4_4` as if you add new k8s version are always based on the latest and this would mean that the latest doesn't have the changes

**Pull request merged**
