### PR TITLE
v_3_0_0: update hyperkube to v1.9.0

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by puja108** [comment]
Btw, this might need quite some testing, as there's lots of change sin the backlog. Sonobuoy conformance plugin is not updated to 1.9 yet, but I have a PR ofr that, until then we might test with latest (1.8.5).

**Comment by kopiczko** [comment]
I retagged it moment ago: https://github.com/giantswarm/retagger/pull/38

**Comment by xh3b4sd** [comment]
The process is WIP somehow and I just wondered why you did not change https://github.com/giantswarm/k8scloudconfig/blob/master/template.go#L27. It might not be necessary. WDYT? I would like to have a place where we at least write something for ourselves what changes on the bump. Maybe we could just add this to the readme. Uncertain.

**Comment by xh3b4sd** [comment]
And please make sure you remove your merged branches. k8scloudconfig is a mess regarding orphaned branches.

**Comment by kopiczko** [comment]
Re changelog. I'm careful with git commit messages. It's easy to reconstruct the changelog:

```
$ git log --pretty=format:'%s' | grep v_3_0_0
v_3_0_0: update hyperkube to v1.9.0 (#268)
v_3_0_0: allow disabling calico (#267)
v_3_0_0: allow extra manifests (#266)
v_3_0_0: allow setting custom K8s API address for master nodes (#265)
v_3_0_0: allow extra hyperkube options (#264)
v_3_0_0: unify CloudConfig construction (#263)
v_3_0_0: init from v_2_0_0 (#262)
```

**Comment by xh3b4sd** [comment]
The git log magic is not good enough for me. I want to know what the difference between 2 and 3 is. I just want to have one sentence. I think we should document this. Relying on git commit messages is not really reliable.

**Comment by kopiczko** [comment]
I introduced a changelog: https://github.com/giantswarm/k8scloudconfig/pull/278.

**Pull request merged**
