### PR TITLE
ensure namespaces exist

### PR DESCRIPTION
**Pull request by whites11**
needed in clusters where the app-operator is not running)

see https://github.com/giantswarm/k8scloudconfig/pull/609

### CODE REVIEW

**Comment by mazzy89** [comment]
Not fully convinced here. 

That code is put at the beginning of the k8s-addon when the giantswarm namespace still does not exist.

so this code will run always also in the case when app-operator is present.

**Comment by mazzy89** [comment]
Does this make sense here? if e2e does not carry app-operator with them, then it would make sense to create giantswarm ns in azure e2e tests because this is an external dependency

**Comment by whites11** [comment]
That's an option for sure. But we caught only one case (the e2e with missing app-operator). What if there are other cases as well? This unit fails completely if that prerequisite is not met for any reason, leading to non working clusters.
If we can, I reckon we should ensure all prerequisites are fullfilled within this script.
Other opinions welcome!

**Comment by mazzy89** [comment]
I've tested this case for cluster startup on aws azure and kvm but not run e2e tests. the cluster startup which is what we are interested in works. no recall any other cases here whre this could fails.

**Comment by tfussell** [comment]
My initial feeling is that this would make sense to do in `e2e-harness` since it's responsible for setting up clusters in e2e tests. Maybe somewhere around here https://github.com/giantswarm/e2e-harness/blob/master/pkg/framework/guest.go What do you all think?

**Comment by mazzy89** [comment]
agree with @tfussell

**Comment by whites11** [comment]
Sounds good to me. `e2e-harness` is deprecated and we will definitely see this issue again, but it's 2 against one so I'll make the change there.
Thanks for the feedack.

**Pull request closed without merging**
