### PR TITLE
templates: misc fixes

### PR DESCRIPTION
**Pull request by iaguis**
These were found while working on https://github.com/giantswarm/aws-operator/pull/70

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I think we want to merge this into the feature branch and not into master, right?

**Comment by iaguis** [comment]
> I think we want to merge this into the feature branch and not into master, right?

We can do that on the aws-operator repo, but these issues are mistakes that we'll need to fix eventually so I think fixing them on this repo (k8scloudconfig) now is fine. WDYT?

**Comment by xh3b4sd** [comment]
Oh man, this is in k8scloudconfig. All good. I thought we are in aws-operator. No worries, vacation is coming soon. 🎉

**Comment by iaguis** [comment]
Hehe, thanks! 😄

**Pull request merged**
