### PR TITLE
adding RBAC and PSP

### PR DESCRIPTION
**Pull request by puja108**
redo of https://github.com/giantswarm/k8scloudconfig/pull/180 for new directory structure

### CODE REVIEW

**Comment by puja108** [comment]
btw, that +/- 1 line difference to the original PR is because of line 234 (no actual change)

**Comment by calvix** [comment]
yeah probably good idea to retest it on gauss

**Comment by puja108** [comment]
Yeah, I'd also like to make sure after so many things have changed. Would `ginger` also be ready for testing this or do we still need changes to aws-operator to support the new format?

**Comment by xh3b4sd** [comment]
The AWS operator has to be adapted to use the versioned k8scloudconfig. AFAIK Joe just pinned the old version. The task is not that difficult/big but let me know when you need help. Also may check the KVM operator how it is done there.

**Comment by xh3b4sd** [comment]
AWS operator is done.

**Pull request merged**
