### PR TITLE
Increase kubelet hard memory eviction

### PR DESCRIPTION
**Pull request by mazzy89**
Towards https://github.com/giantswarm/giantswarm/issues/8361

### CODE REVIEW

**Comment by mazzy89** [comment]
Do you think this could have an impact on nodes and be disruptive?

**Comment by MarcelMue** [comment]
> Do you think this could have an impact on nodes and be disruptive?

I don't think so - just something where we need to aware that customers might complain?

**Comment by mazzy89** [comment]
then let's communicate in the CHANGELOG of the next release. sound it resonable?

**Comment by MarcelMue** [comment]
> then let's communicate in the CHANGELOG of the next release. sound it resonable?

Works for me :+1:

**Pull request merged**
